"""add column frameworks at Project models

Revision ID: 03f1981c0f3b
Revises: 2e2da0aee9eb
Create Date: 2026-01-06 21:15:55.470094

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '03f1981c0f3b'
down_revision: Union[str, None] = '2e2da0aee9eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('frameworks', postgresql.ARRAY(sa.String()), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'frameworks')
    # ### end Alembic commands ###
