"""Update models and add SystemConfig Model

Revision ID: 1217671bb0f3
Revises: b2858d28616d
Create Date: 2026-01-06 19:24:33.855108

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1217671bb0f3'
down_revision: Union[str, None] = 'b2858d28616d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('system_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('config_key', sa.String(), nullable=True),
    sa.Column('config_value', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_system_configs_config_key'), 'system_configs', ['config_key'], unique=True)
    op.create_index(op.f('ix_system_configs_id'), 'system_configs', ['id'], unique=False)
    op.add_column('blogs', sa.Column('thumbnail_url', sa.String(), nullable=False))
    op.alter_column('projects', 'description',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('projects', 'thumbnail_url',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('projects', 'project_url',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('projects', 'tech_stack',
               existing_type=postgresql.ARRAY(sa.VARCHAR()),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('projects', 'tech_stack',
               existing_type=postgresql.ARRAY(sa.VARCHAR()),
               nullable=True)
    op.alter_column('projects', 'project_url',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('projects', 'thumbnail_url',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('projects', 'description',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('blogs', 'thumbnail_url')
    op.drop_index(op.f('ix_system_configs_id'), table_name='system_configs')
    op.drop_index(op.f('ix_system_configs_config_key'), table_name='system_configs')
    op.drop_table('system_configs')
    # ### end Alembic commands ###
