"""update project models

Revision ID: 9870b6f34ee8
Revises: 6bce39950e37
Create Date: 2026-01-06 21:38:26.365730

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9870b6f34ee8'
down_revision: Union[str, None] = '6bce39950e37'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('tech_stack', postgresql.ARRAY(sa.String()), nullable=False))
    op.drop_column('projects', 'frameworks')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('frameworks', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=False))
    op.drop_column('projects', 'tech_stack')
    # ### end Alembic commands ###
