"""update models

Revision ID: b65975e57be8
Revises: 03f1981c0f3b
Create Date: 2026-01-06 21:17:33.048003

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b65975e57be8'
down_revision: Union[str, None] = '03f1981c0f3b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('last_updated', sa.DateTime(timezone=True), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'last_updated')
    # ### end Alembic commands ###
